# Generated by Django 4.1.6 on 2023-02-09 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "provider_id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("provider_name", models.CharField(max_length=100)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.parent"
                    ),
                ),
            ],
            options={"ordering": ["provider_id"],},
        ),
    ]
