# Generated by Django 4.1.6 on 2023-02-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="Timecode",
            fields=[
                ("time_code", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "time_code_desc",
                    models.TextField(blank=True, max_length=75, null=True),
                ),
                ("time_code_hours", models.IntegerField(blank=True, null=True)),
            ],
            options={"ordering": ["time_code"],},
        ),
    ]
