# Generated by Django 4.1.6 on 2023-02-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_timecode"),
    ]

    operations = [
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "type_id",
                    models.CharField(max_length=1, primary_key=True, serialize=False),
                ),
                ("type_name", models.CharField(max_length=15)),
            ],
        ),
    ]
