# Generated by Django 4.1.6 on 2023-02-09 21:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Engagement",
            fields=[
                ("engagement_id", models.AutoField(primary_key=True, serialize=False)),
                ("srg_id", models.CharField(max_length=20)),
                ("start_date", models.DateField()),
                ("fye", models.DateField(blank=True, null=True)),
                ("budget_amount", models.IntegerField(default=10000, null=True)),
                ("budget_hours", models.IntegerField(default=120)),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "complete_date",
                    models.DateField(blank=True, default=datetime.date.today),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.parent"
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.provider"
                    ),
                ),
                (
                    "time_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.timecode"
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.type"
                    ),
                ),
            ],
        ),
    ]
