# Generated by Django 4.1.6 on 2023-02-09 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0006_engagement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignments",
            fields=[
                ("assignment_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.engagement"
                    ),
                ),
            ],
        ),
    ]
